dist: trusty
sudo: false

language: scala

scala:
  - 2.12.4
  - 2.11.11

jdk: oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls